# Working with Data Frames in Pandas

- Pandas data frames are very convenient to work with. They have dedicated functions to read and write files and perform common mathematical operations similarly to NumPy arrays, and where they do not have direct support, NumPy functions can be used instead. They are also quite flexible about reorganizing columns, and selecting subsets of rows.

Reading and Writing Data Frames in Pandas

In [ ]:
import pandas as pd

In [ ]:
boston = pd.read_csv("https://raw.githubusercontent.com/bu-cds-omds/dx602-examples/main/data/boston-TMAX.tsv",
                                  sep="\t")
boston

          stations        date element  value mflag qflag sflag
0      USC00198368  1994-07-01    TMAX    283                 Z
1      USC00198368  1994-07-02    TMAX    289                 Z
2      USC00198368  1994-07-03    TMAX    283                 Z
3      USC00198368  1994-07-04    TMAX    289                 Z
4      USC00198368  1994-07-05    TMAX    278                 Z
...            ...         ...     ...    ...   ...   ...   ...
10854  USC00198368  2024-05-12    TMAX    133                 H
10855  USC00198368  2024-05-13    TMAX    150                 H
10856  USC00198368  2024-05-14    TMAX    206                 H
10857  USC00198368  2024-05-15    TMAX    228                 H
10858  USC00198368  2024-05-16    TMAX    206                 H

[10859 rows x 7 columns]

- Pandas can read the data file given the URL, the web link, to the data file.

In [ ]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10859 entries, 0 to 10858
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stations  10859 non-null  object
 1   date      10859 non-null  object
 2   element   10859 non-null  object
 3   value     10859 non-null  int64
 4   mflag     10859 non-null  object
 5   qflag     10859 non-null  object
 6   sflag     10859 non-null  object
dtypes: int64(1), object(6)
memory usage: 594.0+ KB

- The various flags include information about the reading including whether something was anomalous.
- Most of these columns were loaded as strings, but the value column was recognized as integer data.

In [ ]:
boston["value"].min(), boston["value"].max()

(np.int64(-139), np.int64(394))

In [ ]:
boston["tmax"] = boston["value"] / 10
boston["tmax"]

0        28.3
1        28.9
2        28.3
3        28.9
4        27.8
         ...
10854    13.3
10855    15.0
10856    20.6
10857    22.8
10858    20.6
Name: tmax, Length: 10859, dtype: float64

- Note that it figured out to switch to float64 where the raw value was an int64 before.
- Let's drop that raw value now.

In [ ]:
boston = boston.drop(["value"], axis=1)
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10859 entries, 0 to 10858
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stations  10859 non-null  object
 1   date      10859 non-null  object
 2   element   10859 non-null  object
 3   mflag     10859 non-null  object
 4   qflag     10859 non-null  object
 5   sflag     10859 non-null  object
 6   tmax      10859 non-null  float64
dtypes: float64(1), object(6)
memory usage: 594.0+ KB

- I reassigned to the boston variable since the drop function created a new data frame.
- The axis parameter was to specify that we were dropping a column instead of a row.
- Let's shrink the columns to just date and the max temperature, and save it to a file.

In [ ]:
boston = boston[["date", "tmax"]]
boston

             date  tmax
0      1994-07-01  28.3
1      1994-07-02  28.9
2      1994-07-03  28.3
3      1994-07-04  28.9
4      1994-07-05  27.8
...           ...   ...
10854  2024-05-12  13.3
10855  2024-05-13  15.0
10856  2024-05-14  20.6
10857  2024-05-15  22.8
10858  2024-05-16  20.6

[10859 rows x 2 columns]

In [ ]:
boston.to_csv("boston.tsv", sep="\t")

In [ ]:
!head boston.tsv

	date	tmax
0	1994-07-01	28.3
1	1994-07-02	28.9
2	1994-07-03	28.3
3	1994-07-04	28.9
4	1994-07-05	27.8
5	1994-07-06	32.8
6	1994-07-07	33.3
7	1994-07-08	32.2
8	1994-07-09	31.1

In [ ]:
boston.to_csv("boston.tsv", sep="\t", index=False)

In [ ]:
!head boston.tsv

date	tmax
1994-07-01	28.3
1994-07-02	28.9
1994-07-03	28.3
1994-07-04	28.9
1994-07-05	27.8
1994-07-06	32.8
1994-07-07	33.3
1994-07-08	32.2
1994-07-09	31.1

Computing with Data Frames

What can be computed with a data frame?
- Anything that you can compute with NumPy
- Anything that you can express as a Python function

- Data frames do not help you compute things that you could not compute with NumPy or pure Python.
- Data frames do make some computations a lot easier.

What is easier to compute with a data frame?
- Cases with missing data (NaN)
- Cases with mismatched data

- Data frame functions make handling missing data a lot easier.
- NumPy does have a fillna function to fill in missing data, but you have to call it separately for each input.
- Pandas functions for computing usually have a fill_value option that you add and it takes care of all the inputs.
- The other thing that gets a lot easier with data frames is that they take care of matching up the rows between data frames.
- If you have sources of data with slightly different coverage, a few missing rows in the beginning will lead to your data not lining up at all.
- Instead of computing nonsensical answers from mismatched pairs of rows, pandas will take care of the alignment and match up rows with the same labels.
- For the cases where the labels are missing on one side or the other, pandas will put NaN, or Not a Number, in the output.
Unless you used the fill_value option which will handle those cases too.

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df1

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
df2 = pd.DataFrame({"a": [4, 5, 6], "c": [7, 8, 9]}, index=[0, 2, 3])
df2

   a  c
0  4  7
2  5  8
3  6  9

- This data frame skipped index value 1, and added 3 at the end.
- So each side has an index value that the other does not.
- So what happens if we add the A columns together?

In [ ]:
df1["a"] + df2["a"]

0    5.0
1    NaN
2    8.0
3    NaN
Name: a, dtype: float64

- We got a new series that has NaN, or not a number, for both labels where one side was missing.

In [ ]:
(df1["a"] + df2["a"]).fillna(0.0)

0    5.0
1    0.0
2    8.0
3    0.0
Name: a, dtype: float64

- We can fill those in afterwards, but we completely ignored the input values that were available.

In [ ]:
df1["a"].add(df2["a"], fill_value=0)

0    5.0
1    2.0
2    8.0
3    6.0
Name: a, dtype: float64

- Specifying the fill_value lets us use the values that were present.
- To get the same effect with just fillna, it would be longer.

In [ ]:
(df1["a"] + df2["a"]).fillna(df1["a"]).fillna(df2["a"])

0    5.0
1    2.0
2    8.0
3    6.0
Name: a, dtype: float64

- That fills in the original values as defaults, but seems like more work than necessary and error prone.
- This would not be so easy with just NumPy because the rows were not aligned.
- The examples so far were working with individual series.
What about data frames?

In [ ]:
df1.add(df2)

     a   b   c
0  5.0 NaN NaN
1  NaN NaN NaN
2  8.0 NaN NaN
3  NaN NaN NaN

- Operating on data frames matches up both rows and columns, or more precisely, index values and column names.
- In the previous output, the only real results are from the intersection of shared labels and shared columns.

In [ ]:
df1.add(df2, fill_value=0)

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  NaN
2  8.0  6.0  8.0
3  6.0  NaN  9.0

- Like before, you can use the fill_value argument.
- This can still holes, rather not a number values.
- These happen when neither input data frame had a particular index and column combination.
- Generally that would mean one side was missing the index value and the other side was missing the column name.

In [ ]:
df1.add(df2, fill_value=0).fillna(0)

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  0.0
2  8.0  6.0  8.0
3  6.0  0.0  9.0

- You can fill those values in with one last fillna call.
- So you essentially are specifying defaults when one side is missing with fill_value, and both sides are missing with fillna.
- Bear in mind, many use cases will not be expecting so many missing values on both side, so double check if you need to fill in so much.

- NumPy function should work on numeric data in Pandas.
Handle one column at a time...

Difference between fillna() vs. fill_value relates to when and how you handle missing data.
- .fillna() is a method used after you have a DataFrame or Series to replace missing values (NaN) in existing data.
- fill_value is an argument used during the creation or combination of data structures (like pd.read_csv() or operations like merging/reindexing) to supply a default value for any missing spots created during that operation.
    - not for filling missing data that was already there. It's for filling the gaps that are created during a restructuring operation.

Analogy: Imagine you're building a LEGO structure:
- .fillna(): You notice a hole in your existing structure and use a specific LEGO brick (the value) to fill that hole.
- fill_value: You decide that any new piece you have to add to the structure because you changed the blueprint (the operation) should automatically be a specific color (the value) instead of leaving an empty gap.

Column Management with Data Frames
- Changing data frames is just like changing key/values in dictionaries.
    - Key = column name
    - Value = pandas Series
- Adding new columns will not change index values.

- Adding and removing columns from a data frame is pretty straight forward.
- If you think of the data frame as a dictionary with series values, then you have most of what you need.

Code Examples: Adding Data Frame Columns

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"a": [3, 4, 5]})
df

   a
0  3
1  4
2  5

In [ ]:
df["b"] = pd.Series([1, 2, 3])
df

   a  b
0  3  1
1  4  2
2  5  3

- You can assign a series to a data frame column and that just works.

In [ ]:
df["c"] = pd.Series([2,4,6,8,10])
df

   a  b  c
0  3  1  2
1  4  2  4
2  5  3  6

- If you assign a series with extra values, the extra ones are dropped.

In [ ]:
df["d"] = pd.Series([6, 7, 8, 9, 10], index=[0, 2, 4, 6, 8])
df

   a  b  c    d
0  3  1  2  6.0
1  4  2  4  NaN
2  5  3  6  7.0

- More specifically, only index values that are already in the data frame are kept.
- This time, I chose every other index value in the added series, so the data frame has not a number where the index values were skipped.

In [ ]:
df2 = pd.DataFrame({"e2": [1, 2, 3, 4, 5]})
df["e"] = df2["e2"]
df

   a  b  c    d  e
0  3  1  2  6.0  1
1  4  2  4  NaN  2
2  5  3  6  7.0  3

- Most of the time, you will be adding columns of one data frame to another data frame.
- The same index value behavior applies.
- Often, you will be working with a lot data frames with the same index, so they will all match up.
- But other times, pandas will take care of the matching automatically for you.

- It is convenient for pandas to match up data by index value.
- But the index value may not be meaningful if it was automatically assigned.
- Mixing up filtered data frames and independently created series may not behave as expected.

Code Example: Removing Data Frame Columns

In [ ]:
del df["b"]
df

   a  c    d  e
0  3  2  6.0  1
1  4  4  NaN  2
2  5  6  7.0  3

- That is the same syntax as deleting a key from a normal Python dictionary.
- There is also a data frame method drop which returns a copy of the data frame with a row or column removed.

In [ ]:
df.drop("c", axis=1)

   a    d  e
0  3  6.0  1
1  4  NaN  2
2  5  7.0  3

- The drop method's default behavior is to return a new data frame and not change the original data frame.

In [ ]:
df

   a  c    d  e
0  3  2  6.0  1
1  4  4  NaN  2
2  5  6  7.0  3

- If you want the drop method to change the data frame, then you can use the inplace option.

In [ ]:
df.drop("c", axis=1, inplace=True)
df

   a    d  e
0  3  6.0  1
1  4  NaN  2
2  5  7.0  3

- Most data frame methods have this inplace option if you want to update the original data frame instead of returning a new data frame or series.

- TLDR: pretend the data frame is a dictionary of series or columns.

Selecting Subsets of Data Frames
- Pandas data frames have two dimensions, rows and columns.
- You can select a subset of either them.
- You can reorder them simultaneously.

Code Examples: Selecting Columns

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"c1": [0, 3, 6], "c2": [1, 4, 7], "c3": [2, 5, 8]}, index=["r1", "r2", "r3"])
df

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8

- These rows labels, column names, and values were chosen to make it easy for you to follow the reorganization like usual.
- If you index a data frame with a list of column names, a new data frame with those columns in that order will be returned.

In [3]:
df[["c1", "c3"]]

    c1  c3
r1   0   2
r2   3   5
r3   6   8

- You can repeat columns, but I don't recommend it in most cases.

In [4]:
df[["c2", "c2"]]

    c2  c2
r1   1   1
r2   4   4
r3   7   7

- The new data frame will use whatever order you listed the column names.

In [5]:
df[["c3", "c2", "c1"]]

    c3  c2  c1
r1   2   1   0
r2   5   4   3
r3   8   7   6

- You can use the iloc attribute to select rows using a list of integers as an index.

In [6]:
df.iloc[[2, 0]]

    c1  c2  c3
r3   6   7   8
r1   0   1   2

- Note the double brackets that I used there.
- The outside pair is for indexing.
- The inside pair is for the list of integer indexes.
- This indexing also works with NumPy arrays.
- If you index iloc with two lists of arrays, you can simultaneously select and reorder both the rows and columns at once.

In [8]:
df.iloc[[2, 0], [1, 2]]
#iloc: integer location based indexing
#[2,0]: a list of row indices you want to keep
#[1,2]: a list of column indices you want to keep

    c2  c3
r3   7   8
r1   1   2

- That also works with NumPy arrays too.
- For both pandas and NumPy, it is usually more common to do this to select data rather than reorder it, but reordering does come up.
- The same pattern of indexing with a list works with the loc attribute where you select rows with labels instead of indexes.

In [9]:
df.loc[["r1", "r3"]]

    c1  c2  c3
r1   0   1   2
r3   6   7   8

- And that works to select row labels and column names together too.

In [10]:
df.loc[["r1", "r3"], ["c1", "c3"]]

    c1  c3
r1   0   2
r3   6   8

- That does not work in NumPy, because NumPy does not have the notion of row labels or column names.
- Matching up this behavior with NumPy, the iloc attribute corresponds to indexing a 2-dimensional NumPy array.
- You can also use slices with iloc and anything else that would work to index a NumPy array.

In [11]:
df.iloc[0::2]

    c1  c2  c3
r1   0   1   2
r3   6   7   8

- One thing that is different between these selections and NumPy behavior is that data sharing like NumPy views is a bit different.

Data Sharing in Pandas

- How does Data Sharing Work in Pandas
  - Many NumPy functions create views to avoid rewriting data
  - Pandas is built on NumPy
  - Does Pandas use views?
    - It depends
    - Pandas developers feel that data sharing in Pandas is unpredictable to users
  - Long Term Answer
    - Copy- on - write behavior
    - Act as if every possible sharing is a copy
    - Only copy if one side writes to the data
    - Available now: pd.options.mode.copy_on_write= True
    - Mandatory in Pandas 3.0...
  - Current Recommendations
    - Treat series as read-only once you finish populating them
    - Replace columns instead of using the in_place option
    - Set pd.options.mode.copy_on_write= True on new projects if you have any concerns