# Working with Data Frames in Pandas

- Pandas data frames are very convenient to work with. They have dedicated functions to read and write files and perform common mathematical operations similarly to NumPy arrays, and where they do not have direct support, NumPy functions can be used instead. They are also quite flexible about reorganizing columns, and selecting subsets of rows.

Reading and Writing Data Frames in Pandas

In [ ]:
import pandas as pd

In [ ]:
boston = pd.read_csv("https://raw.githubusercontent.com/bu-cds-omds/dx602-examples/main/data/boston-TMAX.tsv",
                                  sep="\t")
boston

          stations        date element  value mflag qflag sflag
0      USC00198368  1994-07-01    TMAX    283                 Z
1      USC00198368  1994-07-02    TMAX    289                 Z
2      USC00198368  1994-07-03    TMAX    283                 Z
3      USC00198368  1994-07-04    TMAX    289                 Z
4      USC00198368  1994-07-05    TMAX    278                 Z
...            ...         ...     ...    ...   ...   ...   ...
10854  USC00198368  2024-05-12    TMAX    133                 H
10855  USC00198368  2024-05-13    TMAX    150                 H
10856  USC00198368  2024-05-14    TMAX    206                 H
10857  USC00198368  2024-05-15    TMAX    228                 H
10858  USC00198368  2024-05-16    TMAX    206                 H

[10859 rows x 7 columns]

- Pandas can read the data file given the URL, the web link, to the data file.

In [ ]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10859 entries, 0 to 10858
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stations  10859 non-null  object
 1   date      10859 non-null  object
 2   element   10859 non-null  object
 3   value     10859 non-null  int64
 4   mflag     10859 non-null  object
 5   qflag     10859 non-null  object
 6   sflag     10859 non-null  object
dtypes: int64(1), object(6)
memory usage: 594.0+ KB

- The various flags include information about the reading including whether something was anomalous.
- Most of these columns were loaded as strings, but the value column was recognized as integer data.

In [ ]:
boston["value"].min(), boston["value"].max()

(np.int64(-139), np.int64(394))

In [ ]:
boston["tmax"] = boston["value"] / 10
boston["tmax"]

0        28.3
1        28.9
2        28.3
3        28.9
4        27.8
         ...
10854    13.3
10855    15.0
10856    20.6
10857    22.8
10858    20.6
Name: tmax, Length: 10859, dtype: float64

- Note that it figured out to switch to float64 where the raw value was an int64 before.
- Let's drop that raw value now.

In [ ]:
boston = boston.drop(["value"], axis=1)
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10859 entries, 0 to 10858
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stations  10859 non-null  object
 1   date      10859 non-null  object
 2   element   10859 non-null  object
 3   mflag     10859 non-null  object
 4   qflag     10859 non-null  object
 5   sflag     10859 non-null  object
 6   tmax      10859 non-null  float64
dtypes: float64(1), object(6)
memory usage: 594.0+ KB

- I reassigned to the boston variable since the drop function created a new data frame.
- The axis parameter was to specify that we were dropping a column instead of a row.
- Let's shrink the columns to just date and the max temperature, and save it to a file.

In [ ]:
boston = boston[["date", "tmax"]]
boston

             date  tmax
0      1994-07-01  28.3
1      1994-07-02  28.9
2      1994-07-03  28.3
3      1994-07-04  28.9
4      1994-07-05  27.8
...           ...   ...
10854  2024-05-12  13.3
10855  2024-05-13  15.0
10856  2024-05-14  20.6
10857  2024-05-15  22.8
10858  2024-05-16  20.6

[10859 rows x 2 columns]

In [ ]:
boston.to_csv("boston.tsv", sep="\t")

In [ ]:
!head boston.tsv

	date	tmax
0	1994-07-01	28.3
1	1994-07-02	28.9
2	1994-07-03	28.3
3	1994-07-04	28.9
4	1994-07-05	27.8
5	1994-07-06	32.8
6	1994-07-07	33.3
7	1994-07-08	32.2
8	1994-07-09	31.1

In [ ]:
boston.to_csv("boston.tsv", sep="\t", index=False)

In [ ]:
!head boston.tsv

date	tmax
1994-07-01	28.3
1994-07-02	28.9
1994-07-03	28.3
1994-07-04	28.9
1994-07-05	27.8
1994-07-06	32.8
1994-07-07	33.3
1994-07-08	32.2
1994-07-09	31.1

Computing with Data Frames

What can be computed with a data frame?
- Anything that you can compute with NumPy
- Anything that you can express as a Python function

- Data frames do not help you compute things that you could not compute with NumPy or pure Python.
- Data frames do make some computations a lot easier.

What is easier to compute with a data frame?
- Cases with missing data (NaN)
- Cases with mismatched data

- Data frame functions make handling missing data a lot easier.
- NumPy does have a fillna function to fill in missing data, but you have to call it separately for each input.
- Pandas functions for computing usually have a fill_value option that you add and it takes care of all the inputs.
- The other thing that gets a lot easier with data frames is that they take care of matching up the rows between data frames.
- If you have sources of data with slightly different coverage, a few missing rows in the beginning will lead to your data not lining up at all.
- Instead of computing nonsensical answers from mismatched pairs of rows, pandas will take care of the alignment and match up rows with the same labels.
- For the cases where the labels are missing on one side or the other, pandas will put NaN, or Not a Number, in the output.
Unless you used the fill_value option which will handle those cases too.

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df1

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
df2 = pd.DataFrame({"a": [4, 5, 6], "c": [7, 8, 9]}, index=[0, 2, 3])
df2

   a  c
0  4  7
2  5  8
3  6  9

- This data frame skipped index value 1, and added 3 at the end.
- So each side has an index value that the other does not.
- So what happens if we add the A columns together?

In [ ]:
df1["a"] + df2["a"]

0    5.0
1    NaN
2    8.0
3    NaN
Name: a, dtype: float64

- We got a new series that has NaN, or not a number, for both labels where one side was missing.

In [ ]:
(df1["a"] + df2["a"]).fillna(0.0)

0    5.0
1    0.0
2    8.0
3    0.0
Name: a, dtype: float64

- We can fill those in afterwards, but we completely ignored the input values that were available.

In [ ]:
df1["a"].add(df2["a"], fill_value=0)

0    5.0
1    2.0
2    8.0
3    6.0
Name: a, dtype: float64

- Specifying the fill_value lets us use the values that were present.
- To get the same effect with just fillna, it would be longer.

In [ ]:
(df1["a"] + df2["a"]).fillna(df1["a"]).fillna(df2["a"])

0    5.0
1    2.0
2    8.0
3    6.0
Name: a, dtype: float64

- That fills in the original values as defaults, but seems like more work than necessary and error prone.
- This would not be so easy with just NumPy because the rows were not aligned.
- The examples so far were working with individual series.
What about data frames?

In [ ]:
df1.add(df2)

     a   b   c
0  5.0 NaN NaN
1  NaN NaN NaN
2  8.0 NaN NaN
3  NaN NaN NaN

- Operating on data frames matches up both rows and columns, or more precisely, index values and column names.
- In the previous output, the only real results are from the intersection of shared labels and shared columns.

In [ ]:
df1.add(df2, fill_value=0)

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  NaN
2  8.0  6.0  8.0
3  6.0  NaN  9.0

- Like before, you can use the fill_value argument.
- This can still holes, rather not a number values.
- These happen when neither input data frame had a particular index and column combination.
- Generally that would mean one side was missing the index value and the other side was missing the column name.

In [ ]:
df1.add(df2, fill_value=0).fillna(0)

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  0.0
2  8.0  6.0  8.0
3  6.0  0.0  9.0

- You can fill those values in with one last fillna call.
- So you essentially are specifying defaults when one side is missing with fill_value, and both sides are missing with fillna.
- Bear in mind, many use cases will not be expecting so many missing values on both side, so double check if you need to fill in so much.

- NumPy function should work on numeric data in Pandas.
Handle one column at a time...

Difference between fillna() vs. fill_value relates to when and how you handle missing data.
- .fillna() is a method used after you have a DataFrame or Series to replace missing values (NaN) in existing data.
- fill_value is an argument used during the creation or combination of data structures (like pd.read_csv() or operations like merging/reindexing) to supply a default value for any missing spots created during that operation.
    - not for filling missing data that was already there. It's for filling the gaps that are created during a restructuring operation.

Analogy: Imagine you're building a LEGO structure:
- .fillna(): You notice a hole in your existing structure and use a specific LEGO brick (the value) to fill that hole.
- fill_value: You decide that any new piece you have to add to the structure because you changed the blueprint (the operation) should automatically be a specific color (the value) instead of leaving an empty gap.

Column Management with Data Frames
- Changing data frames is just like changing key/values in dictionaries.
    - Key = column name
    - Value = pandas Series
- Adding new columns will not change index values.

- Adding and removing columns from a data frame is pretty straight forward.
- If you think of the data frame as a dictionary with series values, then you have most of what you need.

Code Examples: Adding Data Frame Columns

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"a": [3, 4, 5]})
df

   a
0  3
1  4
2  5

In [ ]:
df["b"] = pd.Series([1, 2, 3])
df

   a  b
0  3  1
1  4  2
2  5  3

- You can assign a series to a data frame column and that just works.

In [ ]:
df["c"] = pd.Series([2,4,6,8,10])
df

   a  b  c
0  3  1  2
1  4  2  4
2  5  3  6

- If you assign a series with extra values, the extra ones are dropped.

In [ ]:
df["d"] = pd.Series([6, 7, 8, 9, 10], index=[0, 2, 4, 6, 8])
df

   a  b  c    d
0  3  1  2  6.0
1  4  2  4  NaN
2  5  3  6  7.0

- More specifically, only index values that are already in the data frame are kept.
- This time, I chose every other index value in the added series, so the data frame has not a number where the index values were skipped.

In [ ]:
df2 = pd.DataFrame({"e2": [1, 2, 3, 4, 5]})
df["e"] = df2["e2"]
df

   a  b  c    d  e
0  3  1  2  6.0  1
1  4  2  4  NaN  2
2  5  3  6  7.0  3

- Most of the time, you will be adding columns of one data frame to another data frame.
- The same index value behavior applies.
- Often, you will be working with a lot data frames with the same index, so they will all match up.
- But other times, pandas will take care of the matching automatically for you.

- It is convenient for pandas to match up data by index value.
- But the index value may not be meaningful if it was automatically assigned.
- Mixing up filtered data frames and independently created series may not behave as expected.

Code Example: Removing Data Frame Columns

In [ ]:
del df["b"]
df

   a  c    d  e
0  3  2  6.0  1
1  4  4  NaN  2
2  5  6  7.0  3

- That is the same syntax as deleting a key from a normal Python dictionary.
- There is also a data frame method drop which returns a copy of the data frame with a row or column removed.

In [ ]:
df.drop("c", axis=1)

   a    d  e
0  3  6.0  1
1  4  NaN  2
2  5  7.0  3

- The drop method's default behavior is to return a new data frame and not change the original data frame.

In [ ]:
df

   a  c    d  e
0  3  2  6.0  1
1  4  4  NaN  2
2  5  6  7.0  3

- If you want the drop method to change the data frame, then you can use the inplace option.

In [ ]:
df.drop("c", axis=1, inplace=True)
df

   a    d  e
0  3  6.0  1
1  4  NaN  2
2  5  7.0  3

- Most data frame methods have this inplace option if you want to update the original data frame instead of returning a new data frame or series.

- TLDR: pretend the data frame is a dictionary of series or columns.

Selecting Subsets of Data Frames
- Pandas data frames have two dimensions, rows and columns.
- You can select a subset of either them.
- You can reorder them simultaneously.

Code Examples: Selecting Columns

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"c1": [0, 3, 6], "c2": [1, 4, 7], "c3": [2, 5, 8]}, index=["r1", "r2", "r3"])
df

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8

- These rows labels, column names, and values were chosen to make it easy for you to follow the reorganization like usual.
- If you index a data frame with a list of column names, a new data frame with those columns in that order will be returned.

In [3]:
df[["c1", "c3"]]

    c1  c3
r1   0   2
r2   3   5
r3   6   8

- You can repeat columns, but I don't recommend it in most cases.

In [4]:
df[["c2", "c2"]]

    c2  c2
r1   1   1
r2   4   4
r3   7   7

- The new data frame will use whatever order you listed the column names.

In [5]:
df[["c3", "c2", "c1"]]

    c3  c2  c1
r1   2   1   0
r2   5   4   3
r3   8   7   6

- You can use the iloc attribute to select rows using a list of integers as an index.

In [6]:
df.iloc[[2, 0]]

    c1  c2  c3
r3   6   7   8
r1   0   1   2

- Note the double brackets that I used there.
- The outside pair is for indexing.
- The inside pair is for the list of integer indexes.
- This indexing also works with NumPy arrays.
- If you index iloc with two lists of arrays, you can simultaneously select and reorder both the rows and columns at once.

In [8]:
df.iloc[[2, 0], [1, 2]]
#iloc: integer location based indexing
#[2,0]: a list of row indices you want to keep
#[1,2]: a list of column indices you want to keep

    c2  c3
r3   7   8
r1   1   2

- That also works with NumPy arrays too.
- For both pandas and NumPy, it is usually more common to do this to select data rather than reorder it, but reordering does come up.
- The same pattern of indexing with a list works with the loc attribute where you select rows with labels instead of indexes.

In [9]:
df.loc[["r1", "r3"]]

    c1  c2  c3
r1   0   1   2
r3   6   7   8

- And that works to select row labels and column names together too.

In [10]:
df.loc[["r1", "r3"], ["c1", "c3"]]

    c1  c3
r1   0   2
r3   6   8

- That does not work in NumPy, because NumPy does not have the notion of row labels or column names.
- Matching up this behavior with NumPy, the iloc attribute corresponds to indexing a 2-dimensional NumPy array.
- You can also use slices with iloc and anything else that would work to index a NumPy array.

In [11]:
df.iloc[0::2]

    c1  c2  c3
r1   0   1   2
r3   6   7   8

- One thing that is different between these selections and NumPy behavior is that data sharing like NumPy views is a bit different.

Data Sharing in Pandas

- How does Data Sharing Work in Pandas
  - Many NumPy functions create views to avoid rewriting data
  - Pandas is built on NumPy
  - Does Pandas use views?
    - It depends
    - Pandas developers feel that data sharing in Pandas is unpredictable to users
  - Long Term Answer
    - Copy- on - write behavior
    - Act as if every possible sharing is a copy
    - Only copy if one side writes to the data
    - Available now: pd.options.mode.copy_on_write= True
    - Mandatory in Pandas 3.0...
  - Current Recommendations
    - Treat series as read-only once you finish populating them
    - Replace columns instead of using the in_place option
    - Set pd.options.mode.copy_on_write= True on new projects if you have any concerns

Data Indexing and Selection
  - Data Selection in Series
    - Series object acts in many ways like a one-dimensional NumPy array, and in many ways like a standard Python dictionary
  - Series as dictionary
      - Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values:

In [17]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [18]:
data['b']

np.float64(0.5)

- We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [19]:
'a' in data

True

In [20]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [21]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

- Series objects can even be modified with a dictionary-like syntax. Just as you can extend a dictionary by assigning to a new key, you can extend a Series by assigning to a new index value:

In [22]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

- This easy mutability of the objects is a convenient feature: under the hood, Pandas is making decisions about memory layout and data copying that might need to take place; the user generally does not need to worry about these issues.

  - Series as one-dimensional array
    - A Series builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays, that is, slices, masking, and fancy indexing. Examples of these are as follows:

In [23]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [24]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [25]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [26]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

- When slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice.

  - Indexers: loc, iloc, ix
    - If your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [27]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [28]:
# explicit index when indexing
data[1]

'a'

In [29]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

- Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.

- First, the loc attribute allows indexing and slicing that always references the explicit index:

In [30]:
data.loc[1]

'a'

In [31]:
data.loc[1:3]

1    a
3    b
dtype: object

- The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

In [32]:
data.iloc[1]

'b'

In [33]:
data.iloc[1:3]

3    b
5    c
dtype: object

- A third indexing attribute, ix, is a hybrid of the two, and for Series objects is equivalent to standard []-based indexing. The purpose of the ix indexer will become more apparent in the context of DataFrame objects
- One guiding principle of Python code is that "explicit is better than implicit." The explicit nature of loc and iloc make them very useful in maintaining clean and readable code; especially in the case of integer indexes, I recommend using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

Data Selection in DataFrame
-  DataFrame acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of Series structures sharing the same index.

DataFrame as a dictionary
- DataFrame as a dictionary of related Series objects.

In [34]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

- The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:

In [36]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

- Equivalently, we can use attribute-style access with column names that are strings:

In [37]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

- This attribute-style column access actually accesses the exact same object as the dictionary-style access:

In [38]:
data.area is data['area']

True

- Though this is a useful shorthand, keep in mind that it does not work for all cases! For example, if the column names are not strings, or if the column names conflict with methods of the DataFrame, this attribute-style access is not possible. For example, the DataFrame has a pop() method, so data.pop will point to this rather than the "pop" column:

In [39]:
data.pop is data['pop']

False

- In particular, you should avoid the temptation to try column assignment via attribute (i.e., use data['pop'] = z rather than data.pop = z).

- Like with the Series objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [40]:
data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

- This shows a preview of the straightforward syntax of element-by-element arithmetic between Series objects

- DataFrame as two-dimensional array
  - View the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute:

In [41]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

- Transpose the full DataFrame to swap rows and columns:

In [42]:
data.T

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

- When it comes to indexing of DataFrame objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row:

In [43]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

- And passing a single "index" to a DataFrame accesses a column:

In [44]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

- Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. Using the iloc indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [45]:
data.iloc[:3, :2]

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

- Similarly, using the loc indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [46]:
data.loc[:'Illinois', :'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

- The ix indexer allows a hybrid of these two approaches:

In [53]:
data.loc[:data.index[2], :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

- Keep in mind that for integer indices, the ix indexer is subject to the same potential sources of confusion as discussed for integer-indexed Series objects.

- Any of the familiar NumPy-style data access patterns can be used within these indexers. For example, in the loc indexer we can combine masking and fancy indexing as in the following:

In [54]:
data.loc[data.density > 100, ['pop', 'density']]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

- Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [55]:
data.iloc[0, 2] = 90
data

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

Additional Indexing Conventions

- First, while indexing refers to columns, slicing refers to rows:

In [56]:
data['Florida':'Illinois']

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

- Such slices can also refer to rows by number rather than by index:

In [57]:
data[1:3]

            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

- Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [58]:
data[data.density > 100]

            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

- These two conventions are syntactically similar to those on a NumPy array

Operating on Data in Pandas